---
- hosts: pmm-server
  remote_user: "{{ osuser }}"
  become: yes
  become_user: root
  gather_facts: false
  vars_files:
    - mysql_nodes.yml
  tasks:

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start docker
      systemd:
        name: docker
        state: started

    - name: Init docker pmm
      shell: >
        docker pull percona/pmm-server:latest

    - name: Init docker pmm 1
      shell: >
        docker create -v /opt/prometheus/data -v /opt/consul-data -v /var/lib/mysql -v /var/lib/grafana --name pmm-data percona/pmm-server:latest /bin/true

    - name: Start docker pmm 
      shell: >
        docker run -d -p 80:80 --volumes-from pmm-data --name pmm-server --restart always percona/pmm-server:latest
