---
- hosts: worker
  remote_user: "{{ osuser }}"
  become: yes
  become_user: root
 #  gather_facts: true
  vars_files:
    - config_nodes.yml

- hosts: all
  remote_user: "{{ osuser }}"
  become: yes
  become_user: root
  #  gather_facts: true
  serial: 5
  vars_files:
    - config_nodes.yml


  pre_tasks:

  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when:
    - output.stdout != ""
    - output.stdout != "\r\n"
  - name: Gathering Facts
    setup:      

  tasks:

    - import_tasks: network_tasks.yml

#    - name: Install external script
#      shell: >
#        curl -sL https://gist.githubusercontent.com/alexellis/7315e75635623667c32199368aa11e95/raw/b025dfb91b43ea9309ce6ed67e24790ba65d7b67/kube.sh | sudo sh


      #    - name: Update and upgrade apt packages
      #apt:
      #  update_cache: yes
      #
    - name: Remove packages
      apt:
        name: "{{ item }}"
        state: absent
      with_items:
        - kubelet
        - kubeadm
        - kubernetes-cni
        - docker.io

    - name: Install docker
      apt:
        name: docker.io
        state: present

    - name: Install key
      shell: >
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

    - name: Install repo
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present


    - name: Update and upgrade apt packages
      apt:
        update_cache: yes

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - kubelet
        - kubeadm
        - kubernetes-cni

    - name: Disable swap
      shell: >
        swapoff -a

    - name: modprobe br_netfilter
      shell: >
        modprobe br_netfilter

    - name: Fix sysctl
      shell: sysctl net.bridge.bridge-nf-call-iptables=1

    - name: Reset Kubernetes component
      shell: "kubeadm reset --force"

    - name: Remove network plugins
      shell: "rm -f /etc/cni/net.d/*"

      #- name: Reset IPtables
      #shell: "iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X"

