---
osuser: vadim
networkinterface: ansible_enp94s0f0
# Credentials

#master_ip: "{{ hostvars[groups['master'][0]].ansible_eno2.ipv4.address | default(groups['master'][0]) }}"
master_ip: "172.16.0.12"
token: b0f7b8.8d1767876297d85c

#network: kuberouter
#network: calico
network: calicodef
#network: flannel
#network: cilium
#network: weave
