---
- hosts: worker
  remote_user: "{{ osuser }}"
  become: yes
  become_user: root
  gather_facts: true
  vars_files:
    - config_nodes.yml

  tasks:

    - name: Hostname
      hostname: name="node-{{ play_hosts.index(inventory_hostname)|int+1 }}"
