---
- hosts: pmm-server
  remote_user: root
  become: yes
  become_user: root
  tasks:

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes

    - name: Install Docker
      yum:
        name: docker.io
        state: present

    - name: Start docker
      systemd:
        name: docker
        state: started

    - name: Init docker pmm
      shell: >
        docker pull percona/pmm-server:2

    - name: Init docker pmm 
      shell: >
        docker create -v /opt/prometheus/data -v /opt/consul-data -v /var/lib/mysql -v /var/lib/grafana --name pmm-data percona/pmm-server:2 /bin/true

    - name: Start docker pmm 
      shell: >
        docker run -d -p 80:80 -p 443:443 --volumes-from pmm-data --name pmm-server --restart always  percona/pmm-server:2
