---
- hosts: node
  remote_user: "{{ osuser }}"
  become: yes
  become_user: root
  gather_facts: true
  vars_files:
    - mysql_nodes.yml

  tasks:

    - name: Stop MySQL
      systemd:
        name: mysql-cd
        state: stopped

    - name: Remove datadir
      file:
        path: "{{ mountdir }}/{{ mysqldir }}-copy-{{ backupdir }}"
        state: "{{ item }}"
      with_items:
        - absent
      tags: copyfiles

    - name: Check if the msrsync exists.
      command: /usr/bin/test -e /usr/bin/msrsync
      ignore_errors: True
      register: msrsync_exists

    - name: Download msrsync
      get_url:
        url: "https://raw.githubusercontent.com/jbd/msrsync/master/msrsync"
        dest: "/usr/bin/msrsync"
      when: msrsync_exists.rc != 0

    - name: Ansible delete file glob
      find:
        paths: "{{ mountdir }}/{{ mysqldir }}/"
        patterns: binlog.*
      register: files_to_delete

    - name: Ansible remove file glob
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_to_delete.files }}"


    - name: Copy files
      shell:  chmod a+x /usr/bin/msrsync; msrsync -p 8 "{{ mountdir }}/{{ mysqldir }}/" "{{ mountdir }}/{{ mysqldir }}-copy-{{ backupdir }}"
      tags: copyfiles

#      shell: cp -r "{{ mountdir }}/{{ mysqldir }}-copy" "{{ mountdir }}/{{ mysqldir }}"

    - name: Drop cache
      shell: sync; echo 3 > /proc/sys/vm/drop_caches


# vim: set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab
