---
- hosts: node
  remote_user: "{{ osuser }}"
  become: yes
  become_user: root
  gather_facts: false
  vars_files:
    - mysql_nodes.yml

  pre_tasks:

  tasks:

    - import_tasks: root_tasks.yml

    - name: Reload systemctl
      shell: systemctl daemon-reload

