---
- hosts: node
  remote_user: "{{ osuser }}"
  become: yes
  become_user: root
  gather_facts: false
  vars_files:
    - mysql_nodes.yml

  tasks:

    - name: Stop MySQL
      systemd:
        name: mysql-cd
        state: stopped

