---
- hosts: all
  remote_user: "{{ osuser }}"
  become: yes
  become_user: root
  gather_facts: true
  serial: 5
  vars_files:
    - config_nodes.yml


  tasks:

    - shell: echo "-{{ iface }}" > /sys/class/net/bond0/bonding/slaves
      ignore_errors: True

    - shell: ifdown "{{ iface }}"

    - name: Update apt packages
      apt:
        update_cache: yes

    - shell: ifconfig "{{ iface }}" "{{ intip }}" netmask 255.255.255.0 
#mtu 9000
